# render.yaml
services:
  - type: web
    name: music-quality-control-report
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /healthz
    autoDeploy: true
